<!-- begin Breadcrumb-->
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2><?php echo($this->arrBreadcrumb['tituloPagina']); ?></h2>
        <ol class="breadcrumb">
            <?php
            foreach ($this->arrBreadcrumb['segmentos'] as $arrMigalha) {
                ?>
                <li>
                    <?php
                    if ($arrMigalha['link'] == true) {
                        echo('<a href="' . $this->url($arrMigalha['route'], ['action' => $arrMigalha['action'], 'id' => $arrMigalha['id']]) . '">' . $arrMigalha['text'] . '</a>');
                    } else {
                        echo($arrMigalha['text']);
                    }
                    ?>
                </li>
                <?php
            }
            ?>
        </ol>
    </div>
</div>
<!-- begin Breadcrumb-->