<!-- begin Breadcrumb-->
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Página Inicial</h2>
    </div>
    <div class="col-lg-2">

    </div>
</div>
<!-- begin Breadcrumb-->

<!-- begin pagina-->
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <!-- begin content -->
        <div class="ibox-content col-lg-12">

            <!-- begin header post-->
            <div class="m-b-md">
                <a href="#" class="btn btn-white btn-xs pull-right">Edit project</a>
                <h2>Documentação</h2>
            </div>
            <!-- end pagina-->
        </div>
    </div>
    <!-- end content -->

    <div class="row">
        <!-- begin ibox content -->
        <div class="ibox">
            <div class="ibox-content">
                <a href="article.html" class="btn-link">
                    <h2>
                        Bem vindo a documentacao
                    </h2>
                </a>
                <p>
                    Selecione um conteudo a partir do menu a esquerda
                </p>
            </div>
        </div>
        <!-- eng ibox content -->
    </div>
</div>
<!-- end pagina-->