<!-- begin pagina-->
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <!-- begin ibox content -->
        <div class="ibox">
            <div class="ibox-content">
                <a href="article.html" class="btn-link">
                    <h2>
                        Vish... Moio
                    </h2>
                </a>
                <p>
                    Vish mano, bugo o trem ai...
                </p>
                <img src="<?php echo $this->basePath('img/page-errors/data_not_found.png'); ?>" alt="">
            </div>
        </div>
        <!-- eng ibox content -->
    </div>
</div>
<!-- end pagina-->