<!-- begin Breadcrumb-->
<?php echo($this->partial('cookbook/index/breadcrumb-partial', ['arrBreadcrumb' => $arrBreadcrumb])); ?>
<!-- begin Breadcrumb-->

<!-- begin pagina-->
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <!-- begin content -->
        <div class="ibox-content col-lg-12">

            <!-- begin header post-->
            <div class="m-b-md">
                <a href="<?php echo $this->url('criar', array('controller' => 'post', 'action' => 'editar', 'id' => $arrPost->getIdPost())); ?>"
                   class="btn btn-white btn-xs pull-right">Editar Post</a>
                <h1><?php echo($arrPost->getTituloPost()) ?>
                    <small>Postagem</small>
                </h1>

            </div>
            <?php echo($this->partial('cookbook/index/post-partial', ['arrPost' => $arrPost])); ?>
        </div>
    </div>
</div>
<!-- end pagina-->
<!-- eng ibox content -->
<script defer src="<?php echo($this->basePath('js/plugins/codemirror/codemirror.js')); ?>"></script>
<script defer src="<?php echo($this->basePath('js/plugins/codemirror/mode/javascript/javascript.js')); ?>"></script>
<script defer src="<?php echo($this->basePath('js/codeeditor.js')); ?>"></script>