<!-- begin Breadcrumb-->
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2><?php echo($this->arrBreadcrumb['nomeSubcategoria']); ?></h2>
        <ol class="breadcrumb">
            <li>
                <a href="<?php echo $this->url('cookbook', array('action' => 'tipo', 'id' => $this->arrBreadcrumb['idTipo'])); ?>">
                    <?php echo($this->arrBreadcrumb['nomeTipo']); ?>
                </a>
            </li>
            <li>
                <a href="<?php echo $this->url('cookbook', array('action' => 'categoria', 'id' => $this->arrBreadcrumb['idCategoria'])); ?>">
                    <?php echo($this->arrBreadcrumb['nomeCategoria']); ?>
                </a>
            </li>
            <li class="active">
                Listando tudo de <strong><?php echo($this->arrBreadcrumb['nomeSubcategoria']); ?></strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>
<!-- begin Breadcrumb-->

<!-- begin pagina-->
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <!-- begin content -->
        <div class="ibox-content col-lg-12">

            <!-- begin header post-->
            <div class="m-b-md">
                <a href="<?php echo $this->url('criar', array('controller' => 'subcategoria', 'action' => 'visualizar', 'id' => $arrPosts[0]->getIdSubcategoria())); ?>" class="btn btn-white btn-xs pull-right">Visualizar Subcategoria</a>
                <h2><?php echo($arrPosts[0]->getNomeCategoria()) ?></h2>
            </div>
            <!-- end pagina-->
        </div>
    </div>
    <!-- end content -->

    <div class="row">
        <?php
        foreach ($arrPosts as $arrPost) {
            ?>

            <!-- begin ibox content -->
            <div class="ibox">
                <div class="ibox-content">
                    <a href="article.html" class="btn-link">
                        <h2>
                            <?php echo($arrPost->getTituloPost()) ?>
                        </h2>
                    </a>
                    <div class="small m-b-xs">
                        <strong><?php echo($arrPosts[0]->getNomeUser()) ?></strong> <span class="text-muted"><i class="fa fa-clock-o"></i> <?php echo($arrPost->getDataCriacaoPost()); ?></span>
                    </div>
                    <p>
                        <?php echo($arrPost->getConteudoPost()) ?>
                    </p>
                    <div class="row">
                        <div class="col-md-6">
                            <h5>Tags:</h5>
                            <button class="btn btn-primary btn-xs" type="button">Model</button>
                            <button class="btn btn-white btn-xs" type="button">Publishing</button>
                        </div>
                        <div class="col-md-6">
                            <div class="small text-right">
                                <h5>Stats:</h5>
                                <div><i class="fa fa-comments-o"> </i> 56 comments</div>
                                <i class="fa fa-eye"> </i> 144 views
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- eng ibox content -->
            <?php
        }
        ?>
    </div>


</div>
</div>
<!-- end pagina-->