<!-- begin Breadcrumb-->
<?php echo($this->partial('cookbook/index/breadcrumb-partial', ['arrBreadcrumb' => $arrBreadcrumb])); ?>
<!-- begin Breadcrumb-->

<!-- begin pagina-->
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">

        <!--barra lateral-->
        <div class="col-lg-3">
            <div class="ibox">
                <div class="ibox-content mailbox-content">
                    <div class="file-manager">
                        <a class="btn btn-block btn-primary compose-mail" href="mail_compose.html">Criar</a>
                        <div class="space-25"></div>
                        <h5><?php echo($arrPosts[0]->getNomeSubcategoria()) ?></h5>

                        <ul class="menu-lateral-corpo">
                            <?php
                            foreach ($this->arrMenu as $menu) {
                                ?>
                                <li>
                                    <a href="#">
                                        <span class="nav-label"><?php echo($menu['infos']['nome']) ?></span
                                    </a>
                                    <?php
                                    if (count($menu['arrCategoria'])) {
                                        ?>
                                        <ul> <?php
                                            foreach ($menu['arrCategoria'] as $categoria) {
                                                ?>
                                                <li>
                                                    <a href="<?php echo $this->url('cookbook', array('controller' => 'index', 'action' => 'categoria', 'id' => $categoria['infos']['id'])); ?>"><?php echo($categoria['infos']['nome']) ?> </a>
                                                    <?php
                                                    if (count($categoria['arrSubcategoria'])) {
                                                        ?>
                                                        <ul> <?php
                                                            foreach ($categoria['arrSubcategoria'] as $subcategoria) {
                                                                ?>
                                                                <li>
                                                                    <a href="<?php echo $this->url('cookbook', array('controller' => 'index', 'action' => 'subcategoria', 'id' => $subcategoria['infos']['id'])); ?>"><?php echo($subcategoria['infos']['nome']) ?></a>
                                                                </li>
                                                                <?php
                                                            }
                                                            ?>
                                                        </ul>
                                                        <?php
                                                    }
                                                    ?>
                                                </li>
                                                <?php
                                            }
                                            ?>
                                        </ul>
                                        <?php
                                    }
                                    ?>
                                </li>
                                <?php
                            }
                            ?>
                        </ul>

                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
        </div>
        <!--barra lateral-->

        <!-- begin content -->
        <div class="col-lg-9">
            <div class="ibox">
                <div class="ibox-content">

                    <!-- begin header post-->
                    <div class="m-b-md">
                        <a href="<?php echo $this->url('criar', array('controller' => 'subcategoria', 'action' => 'visualizar', 'id' => $arrPosts[0]->getIdSubcategoria())); ?>"
                           class="btn btn-white btn-xs pull-right">Visualizar Subcategoria</a>
                        <h1><?php echo($arrPosts[0]->getNomeSubcategoria()) ?>
                            <small>Subcategoria</small>
                        </h1>

                        <div class="row">
                            <div class="col-lg-12">
                                <dl class="dl-horizontal">
                                    <dt>Descrição:</dt>
                                    <dd><?php echo($arrPosts[0]->getDescricaoSubcategoria()) ?></dd>
                                    <dt>Categoria:</dt>
                                    <dd><?php echo($arrPosts[0]->getNomeCategoria()) ?></dd>
                                    <dt>Data de criação:</dt>
                                    <dd><?php echo($arrPosts[0]->getDataCriacaoSubcategoria()) ?></dd>
                                    <dt>Postagens:</dt>
                                    <dd><?php echo(count($arrPosts)) ?></dd>
                                </dl>
                            </div>
                        </div>
                    </div>

                    <h2>Postagens</h2>
                    <hr>
                    <?php
                    foreach ($arrPosts as $arrPost) {
                        echo($this->partial('cookbook/index/post-partial', ['arrPost' => $arrPost]));
                    }
                    ?>
                </div>

            </div>
        </div>
    </div>
</div>
<!-- end pagina-->
<!-- eng ibox content -->
<script defer src="<?php echo($this->basePath('js/plugins/codemirror/codemirror.js')); ?>"></script>
<script defer
        src="<?php echo($this->basePath('js/plugins/codemirror/mode/javascript/javascript.js')); ?>"></script>
<script defer src="<?php echo($this->basePath('js/codeeditor.js')); ?>"></script>