<!-- begin Breadcrumb-->
<?php echo($this->partial('cookbook/index/breadcrumb-partial', ['arrBreadcrumb' => $arrBreadcrumb])); ?>
<!-- begin Breadcrumb-->

<!-- begin pagina-->
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <!-- begin content -->
        <div class="ibox-content col-lg-12">

            <!-- begin header post-->
            <div class="m-b-md">
                <a href="<?php echo $this->url('criar', array('controller' => 'tipo', 'action' => 'visualizar', 'id' => $arrPosts[0]->getIdTipo())); ?>"
                   class="btn btn-white btn-xs pull-right">Visualizar Tipo</a>
                <h1><?php echo($arrPosts[0]->getNomeTipo()) ?> <small>Tipo</small></h1>

                <div class="row">
                    <div class="col-lg-12">
                        <dl class="dl-horizontal">
                            <dt>Descrição:</dt> <dd><?php echo($arrPosts[0]->getDescricaoTipo()) ?></dd>
                            <dt>Data de criação:</dt> <dd><?php echo($arrPosts[0]->getDataCriacaoTipo()) ?></dd>
                            <dt>Postagens:</dt> <dd><?php echo(count($arrPosts)) ?></dd>
                        </dl>
                    </div>
                </div>
            </div>

            <h2>Postagens</h2>
            <hr>
            <?php
            foreach ($arrPosts as $arrPost) {
                echo($this->partial('cookbook/index/post-partial', ['arrPost' => $arrPost]));
            }
            ?>




        </div>
    </div>
</div>
<!-- end pagina-->
<script defer src="<?php echo($this->basePath('js/plugins/codemirror/codemirror.js')); ?>"></script>
<script defer src="<?php echo($this->basePath('js/plugins/codemirror/mode/javascript/javascript.js')); ?>"></script>
<script defer src="<?php echo($this->basePath('js/codeeditor.js')); ?>"></script>