<!-- begin Breadcrumb-->
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Categorias</h2>
        <ol class="breadcrumb">
            <li>
                Listando todos
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>
<!-- begin Breadcrumb-->

<!-- begin pagina-->
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <!-- begin content -->
        <div class="ibox-content col-lg-12">

            <!-- begin header post-->
            <div class="m-b-md">
                <a href="<?php echo $this->url('criar', array('controller' => 'categoria', 'action' => 'adicionar')); ?>"
                   class="btn btn-white btn-xs pull-right">Adicionar</a>
                <h2>Categorias
                    <small>Listando todos</small>
                </h2>
            </div>
            <!-- end pagina-->
        </div>
    </div>
    <!-- end content -->

    <div class="row">
        <!-- begin ibox content -->
        <div class="ibox">
            <div class="ibox-content">

                <?php
                echo $this->flashMessenger()->renderCurrent('error', array('alert', 'alert-dismissible', 'alert-danger'));
                echo $this->flashMessenger()->renderCurrent('info', array('alert', 'alert-dismissible', 'alert-info'));
                echo $this->flashMessenger()->renderCurrent('default', array('alert', 'alert-dismissible', 'alert-warning'));
                echo $this->flashMessenger()->renderCurrent('success', array('alert', 'alert-dismissible', 'alert-success'));
                ?>

                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover dataTables-example">
                        <thead>
                        <tr>
                            <th>Id</th>
                            <th>Tipo</th>
                            <th>Nome</th>
                            <th>Data Criação</th>
                            <th>Ações</th>
                        </tr>
                        </thead>
                        <tbody>

                        <?php

                        foreach ($this->arrEntitys as $arrEntity) {
                            ?>
                            <tr>
                                <td><?php echo($arrEntity->getId()); ?></td>
                                <td><?php echo($arrEntity->getTipo()->getNome()); ?></td>
                                <td><?php echo($arrEntity->getNome()); ?></td>
                                <td><?php echo($arrEntity->getDataCriacao()); ?></td>
                                <td>
                                    <a href="<?php echo $this->url('criar', array('controller' => 'categoria', 'action' => 'visualizar', 'id' => $arrEntity->getId())); ?>">
                                        <i class="fa fa-eye"></i>
                                    </a>
                                    <a href="<?php echo $this->url('criar', array('controller' => 'categoria', 'action' => 'editar', 'id' => $arrEntity->getId())); ?>">
                                        <i class="fa fa-pencil-square-o"></i>
                                    </a>
                                    <a href="<?php echo $this->url('criar', array('controller' => 'categoria', 'action' => 'deletar', 'id' => $arrEntity->getId())); ?>">
                                        <i class="fa fa-trash-o text-navy"></i>
                                    </a>
                                </td>
                            </tr>
                            <?php
                        }

                        ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <!-- eng ibox content -->
    </div>

</div>
<!-- end pagina-->
<!-- Data Tables -->
<script defer src="<?php echo($this->basePath('js/datatable.js')); ?>"></script>
<script defer defer src="<?php echo($this->basePath('js/plugins/dataTables/jquery.dataTables.js')); ?>"></script>
<script defer src="<?php echo($this->basePath('js/plugins/dataTables/dataTables.bootstrap.js')); ?>"></script>
<script defer src="<?php echo($this->basePath('js/plugins/dataTables/dataTables.responsive.js')); ?>"></script>
<!-- Page-Level Scripts -->