<!-- begin Breadcrumb-->
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Tipos</h2>
        <ol class="breadcrumb">
            <li>
                Criar
            </li>
            <li>
                Tipos
            </li>
            <li>
                Editar
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>
<!-- begin Breadcrumb-->

<?php
$this->form->setAttribute('action', $this->url('criar', array('controller' => 'tipo', 'action' => 'editar', 'id' => $this->intIdFromRoute)));
/**
 * @var $this->form \Zend\Form\Form
 */
$this->form->prepare();
?>
<!-- begin pagina-->
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <!-- begin content -->
        <div class="ibox-content col-lg-12">

            <!-- begin header post-->
            <div class="m-b-md">
                <a href="<?php echo $this->url('criar', array('controller' => 'tipo', 'action' => 'index')); ?>" class="btn btn-white btn-xs pull-right">Voltar</a>
                <h2>Tipo
                    <small>Editar</small>
                </h2>
            </div>
            <!-- end pagina-->
        </div>
    </div>
    <!-- end content -->

    <div class="row">
        <!-- begin ibox content -->
        <div class="ibox">
            <div class="ibox-content">
                <?php
                echo $this->flashMessenger()->renderCurrent('error',   array('alert', 'alert-dismissible', 'alert-danger'));
                echo $this->flashMessenger()->renderCurrent('info',    array('alert', 'alert-dismissible', 'alert-info'));
                echo $this->flashMessenger()->renderCurrent('default', array('alert', 'alert-dismissible', 'alert-warning'));
                echo $this->flashMessenger()->renderCurrent('success', array('alert', 'alert-dismissible', 'alert-success'));
                echo $this->form()->openTag($this->form);
                foreach ($this->form as $element) { ?>
                    <div class="form-group">
                        <?php
                        if ($element->getAttribute('type') != 'submit') {
                            echo('<label class="col-sm-2 control-label" for="' . $element->getAttribute('id') . '">' . $element->getLabel() . '</label>');
                            echo('<div class="col-sm-10">');
                            echo($this->formElement($element));
                            echo($this->formElementErrors($element));
                            echo('</div>');
                        } else {
                            echo('<div class="col-sm-10 col-lg-offset-2">');
                            echo($this->formElement($element));
                            echo('</div>');
                        }
                        ?>
                    </div>
                    <?php
                }
                echo $this->form()->closeTag();
                ?>
            </div>
        </div>
    </div>
</div>
<!-- eng ibox content -->
