<!-- begin Breadcrumb-->
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Tipos</h2>
        <ol class="breadcrumb">
            <li>
                Listando todos
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>
<!-- begin Breadcrumb-->

<!-- begin pagina-->
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <!-- begin content -->
        <div class="ibox-content col-lg-12">

            <!-- begin header post-->
            <div class="m-b-md">
                <a href="#" class="btn btn-white btn-xs pull-right">Edit project</a>
                <h2>Tipo
                    <small>Listando todos</small>
                </h2>
            </div>
            <!-- end pagina-->
        </div>
    </div>
    <!-- end content -->

    <div class="row">
        <!-- begin ibox content -->
        <div class="ibox">
            <div class="ibox-content">

                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover dataTables-example">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Descrição</th>
                                <th>Data Criação</th>
                                <th>Ações</th>
                            </tr>
                        </thead>
                        <tbody>

                        <?php

                        foreach ($arrTipos as $arrTipo) {
                            ?>
                            <tr>
                                <td><?php echo($arrTipo->getId()); ?></td>
                                <td><?php echo($arrTipo->getDescricao()); ?></td>
                                <td><?php echo($arrTipo->getDataCriacao()); ?></td>
                                <td>
                                    <a href="<?php echo $this->url('criar', array('controller' => 'tipo', 'action' => 'editar', 'id' => $arrTipo->getId())); ?>">
                                        <i class="fa fa-pencil-square-o"></i>
                                    </a>
                                    <a href="<?php echo $this->url('criar', array('controller' => 'tipo', 'action' => 'deletar', 'id' => $arrTipo->getId())); ?>">
                                        <i class="fa fa-trash-o text-navy"></i>
                                    </a>
                                </td>
                            </tr>
                            <?php
                        }

                        ?>
                        </tbody>
                        <tfoot>
                            <tr>
                                <th>Id</th>
                                <th>Descrição</th>
                                <th>Data Criação</th>
                                <th>Ações</th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
        <!-- eng ibox content -->
    </div>

</div>
<!-- end pagina-->
<!-- Data Tables -->
<script defer src="<?php echo($this->basePath('js/datatable.js')); ?>"></script>
<script defer defer src="<?php echo($this->basePath('js/plugins/dataTables/jquery.dataTables.js')); ?>"></script>
<script defer src="<?php echo($this->basePath('js/plugins/dataTables/dataTables.bootstrap.js')); ?>"></script>
<script defer src="<?php echo($this->basePath('js/plugins/dataTables/dataTables.responsive.js')); ?>"></script>
<!-- Page-Level Scripts -->