<!-- begin Breadcrumb-->
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Tipos</h2>
        <ol class="breadcrumb">
            <li>
                Criar
            </li>
            <li>
                Tipos
            </li>
            <li>
                Detalhes - <?php echo($this->entity->getDescricaoTipo()) ?>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>
<!-- begin Breadcrumb-->

<!-- begin pagina-->
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <!-- begin content -->
        <div class="ibox-content col-lg-12">

            <!-- begin header post-->
            <div class="m-b-md">
                <a href="<?php echo $this->url('criar', array('controller' => 'tipo', 'action' => 'index')); ?>" class="btn btn-white btn-xs pull-right">Voltar</a>
                <h2><?php echo($this->entity->getDescricaoTipo()) ?></h2>
            </div>
            <!-- end pagina-->
        </div>
    </div>
    <!-- end content -->

    <div class="row">
        <!-- begin ibox content -->
        <div class="ibox">
            <div class="ibox-content">
                <h3>Detalhes</h3>

                <div class="row">
                    <div class="col-lg-12">
                        <dl class="dl-horizontal">
                            <dt>Descrição:</dt> <dd><?php echo($this->entity->getDescricaoTipo()) ?></dd>
                            <dt>Quantidade de Categorias:</dt> <dd>  <?php echo($this->entity->getQuantidadeCategoria()) ?></dd>
                            <dt>Data de criação:</dt> <dd><?php echo($this->entity->getDataCriacaoTipo()) ?></dd>
                        </dl>
                    </div>
                </div>

                <hr>

                <h3>Categorias</h3>
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover dataTables-example">
                        <thead>
                        <tr>
                            <th>Id</th>
                            <th>Descrição</th>
                            <th>Data Criação</th>
                            <th>Ações</th>
                        </tr>
                        </thead>
                        <tbody>

                        <?php

                        foreach ($arrEntityChilds as $entityChild) {
                            ?>
                            <tr>
                                <td><?php echo($entityChild->getId()); ?></td>
                                <td><?php echo($entityChild->getDescricao()); ?></td>
                                <td><?php echo($entityChild->getDataCriacao()); ?></td>
                                <td>
                                    <a href="<?php echo $this->url('criar', array('controller' => 'categoria', 'action' => 'visualizar', 'id' => $entityChild->getId())); ?>">
                                        <i class="fa fa-eye"></i>
                                    </a>
                                    <a href="<?php echo $this->url('criar', array('controller' => 'categoria', 'action' => 'editar', 'id' => $entityChild->getId())); ?>">
                                        <i class="fa fa-pencil-square-o"></i>
                                    </a>
                                    <a href="<?php echo $this->url('criar', array('controller' => 'categoria', 'action' => 'deletar', 'id' => $entityChild->getId())); ?>">
                                        <i class="fa fa-trash-o text-navy"></i>
                                    </a>
                                </td>
                            </tr>
                            <?php
                        }

                        ?>
                        </tbody>
                        <tfoot>
                        <tr>
                            <th>Id</th>
                            <th>Descrição</th>
                            <th>Data Criação</th>
                            <th>Ações</th>
                        </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- eng ibox content -->
<!-- Data Tables -->
<script defer src="<?php echo($this->basePath('js/datatable.js')); ?>"></script>
<script defer defer src="<?php echo($this->basePath('js/plugins/dataTables/jquery.dataTables.js')); ?>"></script>
<script defer src="<?php echo($this->basePath('js/plugins/dataTables/dataTables.bootstrap.js')); ?>"></script>
<script defer src="<?php echo($this->basePath('js/plugins/dataTables/dataTables.responsive.js')); ?>"></script>
<!-- Page-Level Scripts -->